//created on: Jun 11, 2013
package org.ihtsdo.ttk.services.action;

//list any import classes here.
import javafx.event.Event;
import javafx.scene.input.MouseEvent;
import org.ihtsdo.ttk.services.action.drools.SourceContext;
import org.ihtsdo.ttk.services.action.drools.TargetContext;
import org.ihtsdo.ttk.services.action.terminology.TerminologyMove;
import org.ihtsdo.ttk.services.action.terminology.TerminologyCopy;
import org.ihtsdo.ttk.services.action.terminology.TerminologyLink;

//declare any global variables here

rule "mouse pressed"

    when
       Event(eventType == MouseEvent.MOUSE_PRESSED) from entry-point "user-events";
     then
       System.out.println("Mouse pressed");
  
end


rule "Generate contextual drag actions after mouse pressed"

    when
       Event(eventType == MouseEvent.MOUSE_PRESSED) from entry-point "user-events";
       $targetContext: TargetContext();
       $sourceContext: SourceContext();
     then
       System.out.println("Adding actions");
       $targetContext.getContextualActions().add(new TerminologyCopy($sourceContext.getActionContext(), 
                                                    $targetContext.getActionContext()));
       $targetContext.getContextualActions().add(new TerminologyMove($sourceContext.getActionContext(),
                                                    $targetContext.getActionContext()));     
       $targetContext.getContextualActions().add(new TerminologyLink($sourceContext.getActionContext(),
                                                    $targetContext.getActionContext()));
  
end

rule "Clear contextual drag actions after mouse released"
    // Would be nice to use a constant instead of a string: EntryPoints.USER_EVENTS
    when
       Event(eventType == MouseEvent.MOUSE_RELEASED) from entry-point "user-events";
       $targetContext: TargetContext();
       
    then
       System.out.println("clearing actions");
       $targetContext.getContextualActions().clear();

end
