//created on: Jun 11, 2013
package org.ihtsdo.ttk.services.action

//list any import classes here.
import javafx.scene.input.MouseEvent;
import org.ihtsdo.ttk.services.action.drools.EntryPoints;
import org.ihtsdo.ttk.services.action.terminology.TerminologyMove;
import org.ihtsdo.ttk.services.action.terminology.TerminologyCopy;

//declare any global variables here





rule "Generate contextual drag actions after mouse pressed"

    when
    	MouseEvent(eventType == MouseEvent.MOUSE_PRESSED) from entry-point EntryPoints.USER_EVENTS;
    	$targetContext: TargetContext();
    	$sourceContext: SourceContext();
     then
    	$targetContext.getContextualActions().add(new TerminologyCopy($sourceContext.getActionContext(), 
    															 $targetContext.getActionContext()));
    	$targetContext.getContextualActions().add(new TerminologyMove($sourceContext.getActionContext(),
    															 $targetContext.getActionContext()));     
    	$targetContext.getContextualActions().add(new TerminologyLink($sourceContext.getActionContext(),
    															 $targetContext.getActionContext()));
        

end

rule "Clear contextual drag actions after mouse released"
    //include attributes such as "salience" here...
    when
    	MouseEvent(eventType == MouseEvent.MOUSE_RELEASED) from entry-point EntryPoints.USER_EVENTS;
    	$targetContext: TargetContext();
    	
    then
    	$targetContext.getContextualActions().clear();

end
